### ISSUE TITLE
Access To Slack Client Outside Of Plugins

### ISSUE THREAD

**Issue by pmcintyresfdc** [alexandre-normand/slackscot#154]
## Your Question
Is there a way to access the raw slack.Client outside of a plugin?

## Is your question request related to a problem? 
n/a

## Additional context
I'm trying to use the base bot to send a DM to a user when an interaction is received via a non-slackscot path.

**Comment by pmcintyresfdc** [comment]
For the moment I'm just creating a new client with `viper.GetString("token")`

**Comment by alexandre-normand** [comment]
It's not technically impossible but I think it would break the bot abstraction so I'd be inclined to not offer this. For what it's worth, I think slack applications often do have a bot component and "something else" and that it's okay to share the token for those different components. 

Does that make sense?

**Comment by pmcintyresfdc** [comment]
Yup yup. 
Thanks
