### ISSUE TITLE
Karma plugin: allow multiple users to gain karma in a single post

### ISSUE THREAD

**Issue by saidmasoud** [alexandre-normand/slackscot#161]
## Is your feature request related to a problem? Do you think it's something that needs to be implemented in `slackscot` (versus your integrating `bot`)? Please describe
The karma plugin only works for one user per message. Example: if a user posts the following in a Slack channel/thread, only user1 will gain karma:

```
@user1++ @user2++ @user3++
```

We've often has to individually give karma to multiple users, which is a bit of a pain.

## Describe the solution you'd like
The aforementioned example message should give karma to multiple users all at once. Multiple responses by the Slack bot for each user gaining karma is acceptable.

## Describe alternatives you've considered
N/A
## Additional context

Seems like it would be as simple as iterating over the regexp matches found [here](https://github.com/alexandre-normand/slackscot/blob/master/plugins/karma.go#L162)

**Comment by alexandre-normand** [comment]
@saidmasoud : Oh yeah, that makes sense. And yes, it should be easy to generalize and support multiple karma recordings in the same message. 

Do you want to give that a shot? Otherwise, I can probably do it when I find a few minutes. I believe there are already decent tests to validate the plugin, too. 

Thanks!

**Comment by saidmasoud** [comment]
Sure, I'll take a look when I get a chance!

**Comment by alexandre-normand** [comment]
Awesome. Thanks! Let me know if you run into any issues.

**Comment by alexandre-normand** [comment]
Fixed by PR https://github.com/alexandre-normand/slackscot/pull/162. Thanks, @saidmasoud !
